name: environments

on:
  workflow_dispatch:

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to development
        run: |
          echo "Deploying to ${{ vars.ENV}} with secret ${{ secrets.ADMIN_PASSWORD }} ..."
  prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to production
        run: |
          echo "Deploying to ${{ vars.ENV}} with secret ${{ secrets.ADMIN_PASSWORD }} ..."
